name: Docker CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: CheckOut code
        uses: actions/checkout@v3

      - name: Load .env var
        run: |
          echo "Loading .env var"
          cat .env >> $GITHUB_ENV
          
    
