name: Docker CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: CheckOut code
        uses: actions/checkout@v3

      - name: Display environment variables (secret values will not be printed)
        run: |
            echo "SERVER_IP: $SERVER_IP"
            echo "SERVER_USER: $SERVER_USER"
            echo "VERSION": $DOCKER_TAG
            echo "SSH_PRIVATE_KEY: ***"
          # SSH到远程服务器

      - name: Deploy via SSH and Build Docker Image
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # 进入指定目录（如果没有则创建）
            cd /home/ubuntu/test
        
            # 清除旧的代码和容器
            rm -rf *
            git clone git@github.com:fcihpy001/webserverDemo.git .
        
            # 停止并删除旧容器（如果存在）
            docker stop $DOCKER_IMAGE || true
            docker rm $DOCKER_IMAGE || true
        
            # 构建新的Docker镜像
            docker build -t $DOCKER_IMAGE:$DOCKER_TAG .
        
            # 运行新的Docker容器
            docker run -d --name gin-web -p $PORT:$PORT $DOCKER_IMAGE:$DOCKER_TAG